function detected = predictresult(testImage,sceneFeatures,nFaces)

fcnHandle = @(x) detectFASTFeatures(x,...
	'MinQuality',0.025,...
	'MinContrast',0.025); 
extractorMethod = 'SURF'; 
metric = 'SAD';
boxPoints = fcnHandle(testImage);
[boxFeatures, boxPoints] = extractFeatures(testImage, boxPoints,...
	'Method',extractorMethod,...
	'BlockSize',3,...
	'SURFSize',64);
matchMetric = zeros(size(boxFeatures,1),nFaces);
for ii = 1:nFaces
	[~,matchMetric(:,ii)] = matchFeatures(boxFeatures,sceneFeatures{ii},...
		'MaxRatio',1,...
		'MatchThreshold',100,...
		'Metric',metric);
end
	[~,detected] = min(mean(matchMetric));